// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("chromium")
	ScopeName = "github.com/stuart23/chromiumreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
